# Task1

In [ ]:
def convert_length(value, unit_from, unit_to):
    """
    Convert length between meters and feet.

    Parameters:
        value (float): The numerical value to be converted.
        unit_from (str): The unit of the input value ('m' or 'ft').
        unit_to (str): The desired unit for the output value ('m' or 'ft').

    Returns:
        float: The converted value.
    """
    if unit_from == "m" and unit_to == "ft":
        return value * 3.28084
    elif unit_from == "ft" and unit_to == "m":
        return value / 3.28084
    else:
        raise ValueError("Invalid length conversion units.")

def convert_weight(value, unit_from, unit_to):
    """
    Convert weight between kilograms and pounds.

    Parameters:
        value (float): The numerical value to be converted.
        unit_from (str): The unit of the input value ('kg' or 'lbs').
        unit_to (str): The desired unit for the output value ('kg' or 'lbs').

    Returns:
        float: The converted value.
    """
    if unit_from == "kg" and unit_to == "lbs":
        return value * 2.20462
    elif unit_from == "lbs" and unit_to == "kg":
        return value / 2.20462
    else:
        raise ValueError("Invalid weight conversion units.")

def convert_volume(value, unit_from, unit_to):
    """
    Convert volume between liters and gallons.

    Parameters:
        value (float): The numerical value to be converted.
        unit_from (str): The unit of the input value ('L' or 'gal').
        unit_to (str): The desired unit for the output value ('L' or 'gal').

    Returns:
        float: The converted value.
    """
    if unit_from == "L" and unit_to == "gal":
        return value * 0.264172
    elif unit_from == "gal" and unit_to == "L":
        return value / 0.264172
    else:
        raise ValueError("Invalid volume conversion units.")

def main():
    print("Unit Conversion Program")
    print("Choose a type of conversion:")
    print("1. Length (meters to feet / feet to meters)")
    print("2. Weight (kilograms to pounds / pounds to kilograms)")
    print("3. Volume (liters to gallons / gallons to liters)")

    try:
        choice = int(input("Enter the number of your choice: "))

        if choice == 1:
            print("Length Conversion:")
            unit_from = input("Convert from (m/ft): ").strip().lower()
            unit_to = "ft" if unit_from == "m" else "m"
            value_input = input(f"Enter value in {unit_from}: ").replace(',', '.')
            value = float(value_input)
            result = convert_length(value, unit_from, unit_to)
            print(f"{value} {unit_from} = {result:.2f} {unit_to}")

        elif choice == 2:
            print("Weight Conversion:")
            unit_from = input("Convert from (kg/lbs): ").strip().lower()
            unit_to = "lbs" if unit_from == "kg" else "kg"
            value_input = input(f"Enter value in {unit_from}: ").replace(',', '.')
            value = float(value_input)
            result = convert_weight(value, unit_from, unit_to)
            print(f"{value} {unit_from} = {result:.2f} {unit_to}")

        elif choice == 3:
            print("Volume Conversion:")
            unit_from = input("Convert from (L/gal): ").strip().lower()
            unit_from = unit_from.upper()
            unit_to = "gal" if unit_from == "L" else "L"
            value_input = input(f"Enter value in {unit_from}: ").replace(',', '.')
            value = float(value_input)
            result = convert_volume(value, unit_from, unit_to)
            print(f"{value} {unit_from} = {result:.2f} {unit_to}")

        else:
            print("Invalid choice. Please select a valid option.")

    except ValueError:
        print("Invalid input. Please enter a numeric value using digits and a decimal point (e.g., 3.5).")

if __name__ == "__main__":
    main()


Unit Conversion Program
Choose a type of conversion:
1. Length (meters to feet / feet to meters)
2. Weight (kilograms to pounds / pounds to kilograms)
3. Volume (liters to gallons / gallons to liters)
Enter the number of your choice: 2
Weight Conversion:
Convert from (kg/lbs): kg
Enter value in kg: 10
10.0 kg = 22.05 lbs


# Task2

In [ ]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    Parameters:
        numbers (list of float): The list of numbers.

    Returns:
        float: The sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculate the average of a list of numbers.

    Parameters:
        numbers (list of float): The list of numbers.

    Returns:
        float: The average of the numbers.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot calculate average of an empty list.")
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Find the maximum number in a list.

    Parameters:
        numbers (list of float): The list of numbers.

    Returns:
        float: The maximum number.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find the maximum of an empty list.")
    return max(numbers)

def find_minimum(numbers):
    """
    Find the minimum number in a list.

    Parameters:
        numbers (list of float): The list of numbers.

    Returns:
        float: The minimum number.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find the minimum of an empty list.")
    return min(numbers)

def main():
    print("Mathematical Operations on a List of Numbers")
    print("Choose an operation:")
    print("1. Sum of the numbers")
    print("2. Average of the numbers")
    print("3. Maximum number")
    print("4. Minimum number")

    try:
        choice = int(input("Enter the number of your choice: "))

        if choice not in [1, 2, 3, 4]:
            print("Invalid choice. Please select a valid option.")
            return

        # Get the list of numbers from the user
        user_input = input("Enter a list of numbers (separated by spaces): ")
        number_strings = user_input.split()
        numbers = [float(num.replace(',', '.')) for num in number_strings]  # Handle commas and convert to float

        if len(numbers) == 0:
            print("The list is empty. Please enter at least one number.")
            return

        # Perform the selected operation
        if choice == 1:
            result = calculate_sum(numbers)
            print(f"Sum of the numbers: {result}")

        elif choice == 2:
            result = calculate_average(numbers)
            print(f"Average of the numbers: {result}")

        elif choice == 3:
            result = find_maximum(numbers)
            print(f"Maximum number: {result}")

        elif choice == 4:
            result = find_minimum(numbers)
            print(f"Minimum number: {result}")

    except ValueError:
        print("Invalid input. Please enter numeric values separated by spaces.")

if __name__ == "__main__":
    main()


Mathematical Operations on a List of Numbers
Choose an operation:
1. Sum of the numbers
2. Average of the numbers
3. Maximum number
4. Minimum number
Enter the number of your choice: 2
Enter a list of numbers (separated by spaces): 3
Average of the numbers: 3.0


#4.2 Exercise on List Manipulation:


1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

In [ ]:
def extract_every_other(lst):
    result = []
    for i in range(0, len(lst), 2):
        result.append(lst[i])
    return result

lst = [1, 3, 4, 2, 5, 6]
result = extract_every_other(lst)
print(result)


[1, 4, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]
lst = [1, 2, 3, 4, 5, 6]
result = get_sublist(lst, 1, 4)
print(result)  # Output: [3, 4, 5]


[2, 3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.

In [ ]:
def reverse_list(lst):
    lst.reverse()
    return lst

lst = [1, 2, 3, 4, 5]
result = reverse_list(lst)
print(result)


[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

In [ ]:
def remove_first_last(lst):
    result = []
    for i in range(1, len(lst) - 1):
        result.append(lst[i])
    return result

lst = [1, 2, 3, 4, 5]
result = remove_first_last(lst)
print(result)  # Output: [2, 3, 4]


[2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

In [ ]:
def get_first_n(lst, n):
    return [lst[i] for i in range(n)]
lst = [1, 2, 3, 4, 5]
result = get_first_n(lst, 3)
print(result)


[1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

In [ ]:
def slice(lst, n):
    return lst[len(lst) - n:]

lst = [1, 2, 3, 9, 5]
result = slice(lst, 2)
print(result)

[9, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

In [ ]:
def reverse_order(lst):
    return lst[-2::-2]

print(reverse_order([1, 2, 3, 4, 5, 6]))


[5, 3, 1]


#4.3 Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

In [ ]:
def flatten(lst):
    return [item for sublist in lst for item in sublist]

print(flatten([[1, 2], [3, 4], [5]]))



[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

In [ ]:
def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]

print(access_nested_element(lst, indices))


6


3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.

In [ ]:
def sum_nested(lst):
    total = 0
    for element in lst:
        if isinstance(element, list):
            total += sum_nested(element)
        else:
            total += element
    return total

lst = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(lst))

21


4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.

In [ ]:
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

lst = [[1, 2, 3],  [4, 2], [5]]
elem = 2
print(remove_element(lst, elem))

[[1, 3], [4], [5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.

In [ ]:
def find_max(lst):
    max_val = lst[0]
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)  #
    return max_val


nested_list = [1, [2, 3, [4, 5]], 6, [7, 8], 9]
print(find_max(nested_list))


9


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

In [ ]:
def get_last_n(lst, n):
    return lst[-n:]

my_list = [1, 2, 3, 4, 5, 6, 7]
print(get_last_n(my_list, 3))


[5, 6, 7]


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.

In [ ]:
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

nested_list = [1, [2, [3, [4, 5]]], 6, [7, 8], 9]
print(deep_flatten(nested_list))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.

• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.

In [ ]:
def average_nested(lst):
    flattened_list = [item for sublist in lst for item in sublist]
    return sum(flattened_list) / len(flattened_list) if flattened_list else 0

nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print(result)


3.5


5 About a Numpy.

#Problem - 1: Array Creation:

1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

In [ ]:
array = np.zeros((2, 2))
print(array)


[[0. 0.]
 [0. 0.]]


2. Initialize an all one array with size 4X2.

In [ ]:
array = np.ones((4, 2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
shape = (2, 3)
fillvalue = 7
new_array = np.full(shape, fillvalue)
print(new_array)

[[7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
array = np.array([[1, 2], [3, 4]])
new_array_zeros = np.zeros_like(array)
print(new_array_zeros)

[[0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
array = np.array([[1, 2], [3, 4]])
new_array_ones = np.ones_like(array)
print(new_array_ones)

[[1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1, 2, 3, 4]
array = np.array(new_list)
print(array)

[1 2 3 4]


#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np

In [ ]:
array = np.arange(10, 50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
range = np.arange(9)
matrix = range.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random array:", random_array)
print("Mean of the array:", mean_value)

Random array: [0.73527719 0.89185176 0.48664058 0.3279717  0.69445843 0.2448796
 0.37330369 0.16801037 0.80805122 0.36216309 0.00623159 0.05168325
 0.42356335 0.23099862 0.53774909 0.54947985 0.70262906 0.5480484
 0.44325954 0.80760481 0.6306106  0.916643   0.72783847 0.63252433
 0.6237199  0.84182681 0.05272401 0.80271993 0.37198424 0.44275546]
Mean of the array: 0.5145733970664669


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
random_array = np.random.random((10, 10))
min_value = random_array.min()
max_value = random_array.max()
print("Random 10x10 array:\n", random_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Random 10x10 array:
 [[0.65611107 0.73525218 0.41573548 0.91802867 0.30206965 0.84741723
  0.5859715  0.29970337 0.61754584 0.37690211]
 [0.44943753 0.88983211 0.04469417 0.39566033 0.28356858 0.10034464
  0.99514429 0.1542713  0.10045842 0.22903151]
 [0.96792146 0.72341852 0.74464805 0.86490865 0.75174964 0.14783618
  0.28453828 0.2787347  0.01676487 0.91758485]
 [0.69015281 0.49281404 0.24820909 0.03285476 0.01771667 0.94218654
  0.98693029 0.33908818 0.35975471 0.60762561]
 [0.64586009 0.88036849 0.4567175  0.24174438 0.37381228 0.10851086
  0.91084893 0.50573266 0.02996422 0.72306815]
 [0.89792948 0.32674393 0.5617151  0.01433235 0.13096194 0.90183667
  0.6601114  0.52055432 0.0567739  0.10557942]
 [0.97525014 0.07493481 0.6315482  0.32496475 0.65858969 0.45789326
  0.14566212 0.9150146  0.77555019 0.54314683]
 [0.98310849 0.60590161 0.72522054 0.8187395  0.2929969  0.45498362
  0.59313015 0.10212342 0.94972666 0.22621138]
 [0.11990651 0.83872097 0.29197152 0.71619386 0.16894946 0.

6. Create a zero array of size 10 and replace 5th element with 1.


In [ ]:
z_array = np.zeros(10)
z_array[4] = 1
print(z_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].


In [ ]:
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print(reversed_arr)


[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.


In [ ]:
rows, cols = 5, 5
array = np.ones((rows, cols))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]



9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

1. Add the two array.

In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])


In [ ]:
add_array = x + y
print("Addition of x and y:\n", add_array)


Addition of x and y:
 [[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
subtract_array = x - y
print("Subtraction of x and y:\n", subtract_array)


Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [ ]:
x_multiply = x * 4
y_multiply = y * 5
print("x multiplied by 2:\n", x_multiply, "\n")
print("y multiplied by 3:\n", y_multiply)

x multiplied by 2:
 [[ 4  8]
 [12 20]] 

y multiplied by 3:
 [[25 30]
 [35 40]]


4. Find the square of each element of the array.

In [ ]:
a = np.square(x)
b = np.square(y)
print("Square of each element of x:\n", a, "\n")
print("Square of each element of y:\n", b)

Square of each element of x:
 [[ 1  4]
 [ 9 25]] 

Square of each element of y:
 [[25 36]
 [49 64]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

print("Dot product of v and w:", dot_v_w, "\n")
print("Dot product of x and v:\n", dot_x_v, "\n")
print("Dot product of x and y:\n", dot_x_y)


Dot product of v and w: 219 

Dot product of x and v:
 [29 77] 

Dot product of x and y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
concatenate_xy_rows = np.concatenate((x, y), axis=0)
concatenate_vw_columns = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

print("Concatenation of x and y along rows:\n", concatenate_xy_rows)
print("Concatenation of v and w along columns:\n", concatenate_vw_columns)


Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
try:
    concatenated_x_v = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v:\n", concatenated_x_v)
except Exception as e:
    print(f"Error: {e}")


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


#Problem - 4: Matrix Operations:

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


Prove following with Numpy:
1. Prove A.A−1 = I.

In [ ]:
# Compute the inverse of A
A_inv = np.linalg.inv(A)
# Multiply A with its inverse
A_A_inv = np.dot(A, A_inv)
# Print result
print("A * A^-1:\n", A_A_inv)


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.

In [ ]:
# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)
# Print results
print("AB:\n", AB, "\n")
print("BA:\n", BA)
# Check if AB is equal to BA
print("Does AB equal to BA?", np.array_equal(AB, BA))


AB:
 [[23 13]
 [51 29]] 

BA:
 [[36 44]
 [13 16]]
Does AB equal to BA? False


3. Prove (AB) T = B T A T

In [ ]:
# Compute (AB)^T
AB_T = np.transpose(AB)
# Compute B^T * A^T
BT_AT = np.dot(np.transpose(B), np.transpose(A))
# Print results
print("(AB)^T:\n", AB_T, "\n")
print("B^T * A^T:\n", BT_AT)
# Check if they are equal
print("Does (AB)^T equal to B^T * A^T?", np.array_equal(AB_T, BT_AT))


(AB)^T:
 [[23 51]
 [13 29]] 

B^T * A^T:
 [[23 51]
 [13 29]]
Does (AB)^T equal to B^T * A^T? True


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
# Define matrices
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])
# Compute inverse of A
A_inv_matrix = np.linalg.inv(A_matrix)
# Solve for X
X = np.dot(A_inv_matrix, B_matrix)
# Print solution
print("Solution for x, y, z:", X)


Solution for x, y, z: [ 2.  1. -2.]
